apiVersion: apps/v1
kind: Deployment
metadata:
  name: drain-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drain-test
  template:
    metadata:
      labels:
        app: drain-test
    spec:
      containers:
        - name: nginx
          image: nginx
