apiVersion: v1
kind: Pod
metadata:
  name: memory-leak-test
spec:
  containers:
    - name: leaky-container
      image: busybox
      command:
        [
          "sh",
          "-c",
          "while true; do echo 'Allocating memory'; dd if=/dev/zero of=/dev/null bs=1M count=10; sleep 1; done",
        ]
      resources:
        limits:
          memory: "20Mi"
        requests:
          memory: "20Mi"
