apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-sample-app
  labels:
    app: argocd-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-sample-app
  template:
    metadata:
      labels:
        app: argocd-sample-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-sample-app
spec:
  selector:
    app: argocd-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
