apiVersion: v1
kind: ConfigMap
metadata:
  name: php-memory-leak-script
data:
  memory-leak.php: |
    <?php
    date_default_timezone_set('Asia/Tokyo'); // JSTを設定
    $data = [];
    while (true) {
        $data[] = str_repeat("leak", 1000000); // 約1MBの文字列
        $memoryUsageBytes = memory_get_usage();
        $memoryUsageMB = $memoryUsageBytes / (1024 * 1024); // MBに変換
        echo "[" . date("Y-m-d H:i:s") . "] "; // 現在時刻を出力
        echo "Memory usage: " . $memoryUsageBytes . " bytes (" . round($memoryUsageMB, 2) . " MB)\n";
        sleep(1); // 1秒待機
    }
