apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-memory-leak-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-memory-leak-test
  template:
    metadata:
      labels:
        app: php-memory-leak-test
    spec:
      containers:
        - name: php-leaky-container
          image: php:cli
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
          command: ["php", "/scripts/memory-leak.php"]
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
      volumes:
        - name: script-volume
          configMap:
            name: php-memory-leak-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-memory-leak-script
data:
  memory-leak.php: |
    <?php
    date_default_timezone_set('Asia/Tokyo'); // JSTを設定
    $data = [];
    while (true) {
        $data[] = str_repeat("leak", 1000000); // 約1MBの文字列
        $memoryUsageBytes = memory_get_usage();
        $memoryUsageMB = $memoryUsageBytes / (1024 * 1024); // MBに変換
        echo "[" . date("Y-m-d H:i:s") . "] "; // 現在時刻を出力
        echo "Memory usage: " . $memoryUsageBytes . " bytes (" . round($memoryUsageMB, 2) . " MB)\n";
        sleep(10); // 10秒待機
    }
