apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-test
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # `maxUnavailable: 0, maxSurge: 3` とかにすると設定による挙動の違いがわかって面白い
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: rolling-update-test
  template:
    metadata:
      labels:
        app: rolling-update-test
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
